<?php
$this->config = $this->parent->config;
$this->lang = $this->parent->lang;
?>
<tr class="row-even">
    <td class="small"><?php echo $this->lang->L_SEND_MAIL_FORM?>:</td>
    <td class="small right">
    <?php
        if ($this->config->get('config.email.sendMail') == 0) {
            echo $this->lang->L_NO;
        } else {
            echo $this->lang->L_YES;
        ?>
        <table style="width:100%;" summary="E-Mail parameters">
        <?php if ($this->config->email['attach_backup'] == 0) { ?>
            <tr class="row-even">
                <td class="small right" colspan="2"><?php echo $this->lang->L_DONT_ATTACH_BACKUP?></td>
            </tr>
        <?php } else { ?>
           <tr class="row-even">
                <td class="small right" colspan="2"><?php echo $this->lang->L_ATTACH_BACKUP?></td>
            </tr>
            <tr class="row-odd">
                <td class="small"><?php echo $this->lang->L_MAX_UPLOAD_SIZE?>:</td>
                <td class="small right" colspan="2"><?php echo $d->SEND_MAIL.ATTACH_BACKUP.SIZE?></td>
            </tr>
        <?php } ?>

        <tr class="row-odd">
            <td class="small"><?php echo $this->lang->L_EMAIL_RECIPIENT?>:</td>
            <td class="small right"><?php echo $this->escape($this->config->email['recipient_name'])?></td>
        </tr>
        <?php
            if (count($this->config->email['recipient_cc']) > 0) {
        ?>
        <tr class="row-even">
            <td class="small"><?php echo $this->lang->L_EMAIL_CC?>:</td>
            <?php
                $cc = '';
                    foreach ($this->config->email['recipient_cc'] as $r) {
                       $cc .= $r['name'].', ';
                    }
                    $cc = substr($cc, 0, -2);
            ?>
            <td class="small right"><?php echo $this->escape($cc)?></td>
        </tr>
        <?php } ?>
        </table>
    <?php } ?>
    </td>
</tr>
