<?php
$this->config = $this->parent->config;
$this->lang = $this->parent->lang;

$ftpConfigurations = $this->config->getParam('ftp');
if (count($ftpConfigurations) > 0) {
    $ftpNr = 1;
    foreach ($ftpConfigurations as $ftp) {
        if ($ftp['use'] == 'y') {
?>
    <tr class="row-even">
        <td class="small"><?php echo $this->lang->L_FTP_TRANSFER. ' '. $ftpNr?>:</td>
        <td class="small">
            <table style="width:100%" summary="FTP parameters">
                <tr class="row-even">
                    <td class="small">
                        <?php echo $this->lang->L_FTP_SERVER?>,
                        <?php echo $this->lang->L_FTP_PORT?>,
                        <?php echo $this->lang->L_FTP_USER?>
                    </td>
                    <td class="small right">
                       <?php echo $this->escape($ftp['server'])?>,
                       <?php echo $this->escape($ftp['port'])?>,
                       <?php echo $this->escape($ftp['user'])?>
                    </td>
                </tr>
                <tr class="row-odd">
                    <td class="small"><?php echo $this->lang->L_FTP_DIR?>:</td>
                    <td class="small right"><?php echo $this->escape($ftp['dir'])?></td>
                </tr>
            </table>
        </td>
    </tr>
        <?php } ?>
    <?php } ?>
<?php } ?>
