<?php
$this->lang = Msd_Language::getInstance();
if ($this->pageCount): ?>
<a href="#" <?php if($this->current>1): ?>
    onclick="getLog('<?php echo $this->url(array('action'=>'ajax','offset'=>$this->first)) ?>');"
     accesskey="f" class="Formbutton"><?php echo $this->getIcon('First', '', 16);?>
    <?php else: ?>
        disabled="disabled" class="Formbutton"><?php echo $this->getIcon('FirstDisabled', '', 16);?>
    <?php endif; ?>
</a>

<a href="#" <?php if($this->previous != null): ?>
    onclick="return getLog('<?php echo $this->url(array('action'=>'ajax','offset'=>$this->previous)) ?>');"
    accesskey="c" class="Formbutton">
        <?php echo $this->getIcon('Back', '', 16);?>
    <?php else: ?>
    disabled="disabled" class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
    <?php endif; ?>
</a>
<script type="text/javascript">
$(function() {
    $( "#combobox" ).combobox();
    $( "#toggle" ).click(function() {
        $( "#combobox" ).toggle();
    });
});
</script>

<select id="combobox">
    <?php for($i=1; $i <= $this->pageCount; $i++) { ?>
    <option <?php if ($i == $this->current) echo 'selected="selected"'; ?>><?php echo $i; ?></option>
    <?php } ?>
</select>

<a href="#" <?php if($this->next != null): ?>
    onclick="return getLog('<?php echo $this->url(array('action'=>'ajax','offset'=>$this->next)) ?>');"
    accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
    <?php else: ?>
    disabled="disabled"
    class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
    <?php endif; ?>
</a>
<a href="#" <?php if($this->current<$this->last): ?>
        onclick="getLog('<?php echo $this->url(array('action'=>'ajax','offset'=>$this->last)) ?>');"
        accesskey="f" class="Formbutton"><?php echo $this->getIcon('Last', '', 16);?>
    <?php else: ?>
        disabled="disabled" class="Formbutton"><?php echo $this->getIcon('LastDisabled', '', 16);?>
    <?php endif; ?>
</a>
<?php endif; ?>
