<?php
$lang = Msd_Language::getInstance();

$this->headMeta()->appendHttpEquiv(
    'Content-Type', 'text/html; charset=utf-8'
)
->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
->appendHttpEquiv('pragma', 'no-cache')
->appendHttpEquiv('Cache-Control', 'no-cache')
->appendName('author', 'Daniel Schlichtholz')
->appendName('robots', 'noindex,nofollow');

$this->headScript()->appendFile(
    $this->baseUrl('/js/jquery/jquery.min.js'),
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->baseUrl('/js/jquery/jquery-ui.min.js'),
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->baseUrl('/js/pwdmeter.js'),
    'text/javascript'
);

//and the stylesheet for the ui
$this->headLink()->appendStylesheet(
    $this->baseUrl().'/css/msd/jquery'
    .'/jquery-ui.custom.css'
);

$this->headScript()->appendFile(
    $this->baseUrl('/js/script.js'),
    'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->baseUrl().'/css/msd/style.css'
);
$version = new Msd_Version();
?>
<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>MySQLDumper <?php echo $version->getMsdVersion();?></title>
    <?php
        echo $this->headLink() . "\n";
        echo $this->headMeta() . "\n";
        echo $this->headScript() . "\n";
    ?>
    <style type="text/css">body {direction: ltr;}</style>
</head>

<body>
    <div id="container">
        <div id="fullcontent">
            <h1>
                <img src="<?php echo $this->baseUrl(); ?>/css/msd/pics/menu-headlogo.gif" alt="" />
                <br />
                <?php echo $lang->L_INSTALL;?>: <?php echo $lang->L_MSD_VERSION?> <?php echo $version->getMsdVersion();?>
            </h1>
            <?php echo $this->partial('install/stepIndicator.phtml', $this->stepInfo);?>
            <div id="ajaxContent"><?php echo $this->layout()->content; ?></div>
        </div>
    </div>
</body>
</html>