
<?php
$version = new Msd_Version();
$config = Msd_Configuration::getInstance();
$lang = Msd_Language::getInstance();
$theme = $config->get('config.interface.theme'); //@todo why theme?
$language = $config->get('config.interface.language');
$this->headMeta()->appendHttpEquiv('content-language', $language);
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
    ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
    ->appendHttpEquiv('pragma', 'no-cache')
    ->appendHttpEquiv('Cache-Control', 'no-cache')
    ->appendName('author', 'Daniel Schlichtholz')
    ->appendName('robots', 'noindex,nofollow');

$this->jQuery()->addStylesheet($this->serverUrl() . $this->baseUrl() . '/m/css/jquery.mobile-1.0a4.1.css');
$this->jQuery()->addStylesheet($this->serverUrl() . $this->baseUrl() . '/m/css/mobile.css');
$request = Zend_Controller_Front::getInstance()->getRequest();

$this->jQuery()->addJavascriptFile($this->serverUrl() . $this->baseUrl('/js/script.js'));

$this->jQuery()->setLocalPath($this->serverUrl() . $this->baseUrl() . '/m/js/jquery-1.5.js');
$this->jQuery()->addJavascriptFile($this->serverUrl() . $this->baseUrl() . '/m/js/jquery.mobile-1.0a4.1.js');
$this->jQuery()->addJavascriptFile($this->serverUrl() . $this->baseUrl() . '/m/js/jquery.mobile.carousel.js');
$this->jQuery()->setVersion('1.5');
$this->jQuery()->setUiVersion('1.8.5');
$this->jQuery()->uiEnable();

$messages = (string) $this->popUpMessage();
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    lang="<?php echo $language?>"
    xml:lang="<?php echo $language?>">
<head>
    <title>MySQLDumper Mobile <?php echo $version->getMsdVersion();?></title>
    <?php
        echo (string) $this->jQuery();
        echo $this->headMeta() . "\n";
        echo $this->headScript() . "\n";
    ?>
    <style type="text/css">body {direction: ltr;}</style>
</head>
<body >
        <?php
            echo $messages;
            echo $this->layout()->content;
        ?>
</body>
</html>