<div id="content">
<h2><?php echo $this->lang->L_HOME;?></h2>
    <a href="<?php echo $this->baseUrl();?>/index/phpinfo" class="Formbutton">
        <?php echo $this->getIcon('Info', '', 16);?> PHP-Info
    </a>
<br />
<h3><?php echo $this->lang->L_VERSIONSINFORMATIONEN;?></h3>
<img src="<?php echo $this->baseUrl();?>/css/<?php echo $this->config->getParam('interface.theme');?>/pics/loveyourdata.gif"
    style="float:right;padding-left:10px;" alt="love your data" title="love your data" />
<table class="bdr" summary="Version information">
    <tr class="row-even">
        <td><?php echo $this->lang->L_OS;?>: </td>
        <td><strong><?php echo PHP_OS;?></strong> <?php echo @php_uname();?></td>
    </tr>
    <tr class="row-odd">
        <td><?php echo $this->lang->L_MYSQL_VERSION;?>:</td>
        <td><strong><?php echo $this->mysqlServerVersion;?></strong></td>
    </tr>
    <tr class="row-even">
        <td><?php echo $this->lang->L_MYSQL_CLIENT_VERSION;?>:</td>
        <td><strong><?php echo $this->mysqlClientVersion;?></strong></td>
    </tr>
    <tr class="row-odd">
        <td><?php echo $this->lang->L_PHP_VERSION;?>:</td>
        <td><strong><?php echo PHP_VERSION;?></strong></td>
    </tr>
    <tr class="row-even">
        <td><?php echo $this->lang->L_MEMORY;?>:</td>
        <td>
            <strong>
                <?php echo $this->byteOutput($this->dynamicConfig->getParam('phpRam')*1024*1024, 0);?>
            </strong>
        </td>
    </tr>
    <tr class="row-odd nowrap">
        <td><?php echo $this->lang->L_MAX_EXECUTION_TIME;?>:</td>
        <td>
            <strong><?php echo $this->serverMaxExecutionTime;?>
                <?php echo $this->lang->L_SECONDS;?>
                    (<?php echo $this->dynamicConfig->getParam('maxExecutionTime');?>
                        <?php echo $this->lang->L_SECONDS;?>)
            </strong>
        </td>
    </tr>
    <tr class="row-even nowrap">
        <td><?php echo $this->lang->L_ZEND_FRAMEWORK_VERSION;?>:</td>
        <td><strong><?php echo Zend_Version::VERSION; ?></strong></td>
    </tr>

    <tr class="row-odd">
        <td><?php echo $this->lang->L_PHP_EXTENSIONS;?>:</td>
        <td class="small"><?php echo $this->dynamicConfig->getParam('phpExtensions');?>
            <?php
                if (!$this->dynamicConfig->getParam('compression')) { ?>
                <br /><span class="error"><?php echo $this->lang->L_NOGZPOSSIBLE;?></span>
            <?php }
                if (!extension_loaded('ftp')) { ?>
                    <br /><span class="error"><?php echo $this->lang->L_NOFTPPOSSIBLE;?></span>
            <?php } ?>
        </td>
    </tr>
<?php if ($this->dynamicConfig->getParam('disabledPhpFunctions') > '') { ?>
    <tr class="row-even nowrap">
        <td><?php echo $this->lang->L_DISABLEDFUNCTIONS;?>:</td>
        <td class="small"><?php echo $this->dynamicConfig->getParam('disabledPhpFunctions');?></td>
    </tr>
<?php } ?>
</table>
<br />
<h3><?php echo $this->lang->L_MSD_INFO;?></h3>
<table class="bdr" summary="MySQLDumper Information">
    <tr class="row-even nowrap">
        <td><?php echo $this->lang->L_MSD_VERSION;?>:</td>
        <td><strong><?php echo $this->version->getMsdVersion();?></strong></td>
    </tr>
    <tr class="row-odd">
        <td><?php echo $this->lang->L_DB_ADAPTER;?>:</td>
        <td><strong><?php echo $this->dbAdapter;?></strong></td>
    </tr>
    <tr class="row-even">
        <td><?php echo $this->lang->L_INFO_LOCATION;?>:</td>
        <td><strong><?php echo $_SERVER['SERVER_NAME'];?></strong></td>
    </tr>
    <tr class="row-odd">
        <td><?php echo $this->lang->L_INFO_ACTDB;?>:</td>
        <td><strong><?php echo $this->dynamicConfig->getParam('dbActual');?></strong></td>
    </tr>
    <tr class="row-even">
        <td><?php echo $this->lang->L_FM_FREESPACE;?>:</td>
        <td><strong><?php echo $this->getFreeDiskspace();?></strong></td>
    </tr>
<?php if ($this->filename > '') { ?>
    <tr class="row-odd">
        <td>
            <?php echo $this->lang->L_LASTBACKUP.' '.$this->lang->L_VOM;?>
            <strong><?php echo $this->fileMtime;?></strong>:
        </td>
        <td><strong><?php echo $this->filename;?></strong></td>
    </tr>
<?php } ?>
</table>
</div>
