<tr class="thead">
    <th>&nbsp;</th>
    <th>
        <img src="<?php echo $this->getIconSrc('plus', '');?>"
            class="pointer tooltip"
            title="<?php echo $this->lang->L_SELECT_ALL;?>"
            alt="<?php echo $this->lang->L_SELECT_ALL;?>"
            onclick="checkAll('.dbCheckbox');checkButtonState();"/>
        <img src="<?php echo $this->getIconSrc('minus', '');?>"
             class="pointer tooltip"
             title="<?php echo $this->lang->L_DESELECT_ALL;?>"
             alt="<?php echo $this->lang->L_DESELECT_ALL;?>"
            onclick="unCheckAll('.dbCheckbox');checkButtonState();"/>
    </th>
    <th>#</th>
    <th><?php echo $this->lang->L_DB_NAME;?></th>
    <th>
        <span class="tooltip explain"
            title="<?php echo $this->lang->L_MYSQL_TABLES_EXPLAIN;?>">
            <?php echo $this->lang->L_TABLES;?>
        </span>
    </th>
    <th>
        <span class="tooltip explain"
            title="<?php echo $this->lang->L_DATASIZE_INFO;?>">
            <?php echo $this->lang->L_DATASIZE;?>
        </span>
    </th>
    <th>
        <span class="tooltip explain"
            title="<?php echo $this->lang->L_MYSQL_VIEWS_EXPLAIN;?>">
            <?php echo $this->lang->L_MYSQL_VIEWS;?>
        </span>
    </th>
    <th>
        <span class="tooltip explain"
            title="<?php echo $this->lang->L_MYSQL_ROUTINES_EXPLAIN;?>">
            <?php echo $this->lang->L_MYSQL_ROUTINES;?>
        </span>
    </th>
    <th><?php echo $this->lang->L_DEFAULT_CHARACTER_SET_NAME;?></th>
    <th><?php echo $this->lang->L_DEFAULT_COLLATION_NAME;?></th>
</tr>

