<?php
$prefix            = null;
$optimizeTablesUrl = $this->url(array('controller' => 'sql', 'action' => 'optimize.tables'));
$analyzeTablesUrl  = $this->url(array('controller' => 'sql', 'action' => 'analyze.tables'));
$checkTablesUrl    = $this->url(array('controller' => 'sql', 'action' => 'check.tables'));
$repairTablesUrl   = $this->url(array('controller' => 'sql', 'action' => 'repair.tables'));
$emptyTablesUrl    = $this->url(array('controller' => 'sql', 'action' => 'empty.tables'));
$deleteTablesUrl   = $this->url(array('controller' => 'sql', 'action' => 'delete.tables'));
$createTableUrl    = $this->url(array('controller' => 'sql', 'action' => 'create.table'));
?>
<tr class="thead">
    <th colspan="15">
        <div class="buttonBar">
            <ul class="Formbutton">
                <li>
                    <button class="Formbutton"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $createTableUrl; ?>');">
                        <?php
                            echo $this->getIcon('Tabledata', '' ,16);
                            echo $this->lang->L_NEWTABLE;
                        ?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonOptimize"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $optimizeTablesUrl; ?>');">
                        <?php echo$this->getIcon('Ok', '', 16);?>
                        <?php echo $this->lang->L_OPTIMIZE;?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonAnalyze"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $analyzeTablesUrl; ?>');">
                        <?php echo$this->getIcon('Ok', '', 16);?>
                        <?php echo $this->lang->L_ANALYZE;?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonCheck"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $checkTablesUrl; ?>');">
                        <?php echo$this->getIcon('Ok', '', 16);?>
                        <?php echo $this->lang->L_CHECK;?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonRepair"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $repairTablesUrl; ?>');">
                        <?php echo$this->getIcon('Ok', '', 16);?>
                        <?php echo $this->lang->L_REPAIR;?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonTruncate"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $emptyTablesUrl; ?>');">
                        <?php echo$this->getIcon('delete', '');?>
                        <?php echo $this->lang->L_EMPTY;?>
                    </button>
                </li>
                <li>
                    <button class="Formbutton" disabled="disabled"
                        id="buttonDelete"
                        type="submit"
                        onclick="changeFormAction('.tablesForm', '<?php echo $deleteTablesUrl; ?>');">
                        <?php echo$this->getIcon('delete', '');?>
                        <?php echo $this->lang->L_DELETE;?>
                    </button>
                </li>
            </ul>
        </div>
    </th>
</tr>



