<div id="content">
<h2><?php echo $this->lang->L_RECORDS_OF_TABLE;?> `<?php echo $this->database;?>`.`<?php echo $this->table;?>`</h2>
<?php echo $this->sqlHeadNavi();
if (isset($this->noTables)) { ?>
    <p class="error"><?php echo $this->lang->L_INFO_DBEMPTY;?></p>
<?php
} else {
?>
<table class="bdr" summary="show table data">
    <tr class="thead">
        <th>#</th>
        <?php foreach($this->columns as $row => $value) { ?>
            <th><?php echo $row?></th>
        <?php } ?>
    </tr>
    <?php
    $i = $this->offset+1;
    $cycleHelper = $this->getHelper('cycle')->cycle(array('row-even', 'row-odd'));
    foreach($this->data as $data) {
    ?>
    <tr class="nowrap <?php echo $cycleHelper->next()?>">
        <td class="small right"><?php echo $i; ?>.</td>
        <?php
            foreach($data as $val) { ?>
            <td class="small<?php if(is_numeric($val)) echo " right";?>">
                <?php
                    if ($val !== null) {
                        echo $this->out($val);
                    } else {
                        echo $this->out($val, true, 'i');
                    }
                ?>
            </td>
        <?php
            }
        ?>
    </tr>
    <?php
        $i++;
    };
    if (empty($this->data) && !isset($this->noTables)) {
        echo '<tr><td class="error" colspan="' . (sizeof($this->columns)+1) . '">'
            . $this->lang->L_NO_ENTRIES . '</td></tr>';
    } ?>
</table>
<?php } ?>
</div>