<tr class="thead">
<th>&nbsp;</th>
<th class="toggle">
    <div class="toggleBar" >
    <img src="<?php echo $this->getIconSrc('plus', '');?>"
             class="pointer tooltip"
             title="<?php echo $this->lang->L_SELECT_ALL;?>"
             alt="<?php echo $this->lang->L_SELECT_ALL;?>"
             onclick="checkAll($('[type=checkbox]'));"/>
        <img src="<?php echo $this->getIconSrc('minus', '');?>"
             class="pointer tooltip"
             title="<?php echo $this->lang->L_DESELECT_ALL;?>"
             alt="<?php echo $this->lang->L_DESELECT_ALL;?>"
             onclick="unCheckAll($('[type=checkbox]'));"/>
        </div>
    </th>
    <th class="center">#</th>
    <th>
        <span class="explain tooltip" title="<?php echo $this->lang->L_TABLENAME_EXPLAIN;?>"><?php echo $this->lang->L_TABLENAME;?></span>
    </th>
    <th>
        <span class="explain tooltip" title="<?php echo $this->lang->L_NR_OF_RECORDS;?>"><?php echo $this->lang->L_INFO_RECORDS;?></span>
    </th>
    <th>
        <span class="explain tooltip" title="<?php echo $this->lang->L_DATASIZE;?>"><?php echo $this->lang->L_INFO_SIZE;?></span>
    </th>
    <th>
        <span class="explain tooltip" title="<?php echo $this->lang->L_INDEX_SIZE;?>"><?php echo $this->lang->L_TITLE_INDEX;?></span>
    </th>
    <th class="nowrap">
        <span class="explain tooltip" title="<?php echo $this->lang->L_NEXT_AUTO_INCREMENT;?>"><?php echo $this->lang->L_NEXT_AUTO_INCREMENT_SHORT;?></span>
    </th>
    <th><?php echo $this->lang->L_OVERHEAD;?></th>
    <th><?php echo $this->lang->L_CREATED;?></th>
    <th><?php echo $this->lang->L_INFO_LASTUPDATE;?></th>
    <th><?php echo $this->lang->L_TABLE_TYPE;?></th>
    <th><?php echo $this->lang->L_ENGINE;?></th>
    <th><?php echo $this->lang->L_COLLATION;?></th>
    <th><?php echo $this->lang->L_COMMENT;?></th>
</tr>

