<?php
$i =0;
foreach ($this->databases as $db => $val) {
    $rowclass = $this->cycle(array('row-even','row-odd'))->next();
    if ($db == $this->dbActual) {
        $rowclass = 'row-highlight';
    }
?>

<tr class="<?php echo $rowclass;?>">
    <td class="right"><?php echo$i+1;?>.</td>
    <td>
        <label for="db_multidump_<?php echo$i;?>" style="display:block">
            <?php echo $db;?>
        </label>
    </td>
    <td>
        <input type="checkbox" id="db_multidump_<?php echo$i;?>"
            name="db_multidump_<?php echo$i;?>"
            value="db_multidump_<?php echo$i;?>"
            <?php if ($val['dump'] == 1) {?>
                checked="checked"
            <?php } ?>
            />
    </td>
    <td>
        <input type="text" class="text" name="dbpraefix_<?php echo$i;?>"
            size="10" value="<?php echo $this->escape($val['prefix']);?>" />
        </td>
    <td><?php echo $this->escape($val['command_before_dump']);?></td>
    <td><?php echo $this->escape($val['command_after_dump']);?></td>
</tr>
<?php
    $i++;
}
?>