<?php
$i = 1;
$cycleHelper = $this->getHelper('cycle')->cycle(array('row-even', 'row-odd'));
foreach ($this->processes as $process): ?>
<tr class="<?php echo $cycleHelper->next()?>">
    <td>
        <a href="<?php echo $this->url(array(
            'controller'=>'sql.server',
            'action'=>'kill.process',
            'processId' => $process['Id']));?>">
        <?php echo $this->getIcon('delete', $this->lang->L_KILL_PROCESS);?>
        </a>
        &nbsp;
     </td>
     <td class="right"><?php echo $i;?>.</td>
     <td><?php echo $process['Id'];?></td>
     <td><?php echo $process['User'];?></td>
     <td><?php echo $process['Host'];?></td>
     <td><?php echo $process['db'];?></td>
     <td><?php echo $process['Command'];?></td>
     <td><?php echo $process['Time'];?></td>
     <td><?php echo $process['State'];?></td>
     <td><?php echo $process['Info'];?></td>
</tr>
<?php
++$i;
endforeach; ?>
