<?php
$showVariablesUrl   = $this->url(array('controller'=>'sql.server','action'=>'show.variables'));
$showStatusUrl      = $this->url(array('controller'=>'sql.server','action'=>'show.status'));
$showProcesslistUrl = $this->url(array('controller'=>'sql.server','action'=>'show.processlist'));
$showCharsetsUrl    = $this->url(array('controller'=>'sql.server','action'=>'show.charsets'));

// get action name to set the active item in TabBar
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

// format action name and escape possible dot in action name
$actionName = '"#' . str_replace('.', '\\\.', $actionName) . '"';
?>

<?php $this->jQuery()->javascriptCaptureStart(); ?>

    // set selected tab
    $(document).ready(function() {
        $(<?php echo $actionName; ?>).addClass("ui-state-active");
        $(<?php echo $actionName; ?>).addClass("ui-tabs-selected");
    });

<?php $this->jQuery()->javascriptCaptureEnd(); ?>

<div id="headnavi" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        <li id="show.variables"
            class="ui-state-default ui-corner-top"
            onmouseover="tabOver(this)"
            onmouseout="tabOut(this)">
            <a href="<?php echo $showVariablesUrl;?>">
                <?php echo$this->getIcon('Reports', '', 16);?>
                <?php echo $this->lang->L_MYSQLVARS;?>
            </a>
        </li>
        <li id="show.status"
            class="ui-state-default ui-corner-top"
            onmouseover="tabOver(this)"
            onmouseout="tabOut(this)">
            <a href="<?php echo $showStatusUrl;?>">
                <?php echo$this->getIcon('Reports', '', 16);?>
                <?php echo $this->lang->L_STATUS;?>
            </a>
        </li>
        <li id="show.processlist"
            class="ui-state-default ui-corner-top"
            onmouseover="tabOver(this)"
            onmouseout="tabOut(this)">
            <a href="<?php echo $showProcesslistUrl;?>">
                <?php echo$this->getIcon('Reports', '', 16);?>
                <?php echo $this->lang->L_PROZESSE;?>
            </a>
        </li>
        <li id="show.charsets"
            class="ui-state-default ui-corner-top"
            onmouseover="tabOver(this)"
            onmouseout="tabOut(this)">
            <a href="<?php echo $showCharsetsUrl;?>">
                <?php echo$this->getIcon('Reports', '', 16);?>
                <?php echo $this->lang->L_CHARSETS;?>
            </a>
        </li>
    </ul>
</div>
