<form action="<?php echo $this->formAction; ?>" method="<?php echo $this->formMethod; ?>" enctype="<?php echo $this->formEncType; ?>">
    <div class="paginator">
        <button class="Formbutton first" type="<?php echo $this->buttonType; ?>" onclick="<?php echo $this->first['click']; ?>" accesskey="c"<?php echo $this->first['disabled']; ?>>
            <?php echo $this->getIcon($this->first['icon'], '', 16); ?>
        </button>

        <button class="Formbutton paginator prev" type="<?php echo $this->buttonType; ?>" onclick="<?php echo $this->prev['click']; ?>" accesskey="v"<?php echo $this->prev['disabled']; ?>>
            <?php echo $this->getIcon($this->prev['icon'], '', 16); ?>
        </button>
        <select id="combobox" name="<?php echo $this->urlParam; ?>" onchange="<?php echo $this->onChange; ?>" accesskey="b">
<?php
for ($i = 1; $i <= $this->pageCount; $i++) {
?>
            <option value="<?php echo $i; ?>"<?php echo ($i == $this->currentPage) ? ' selected="selected"' : ''; ?>><?php echo $i; ?></option>
<?php
}
?>
        </select>
        <button class="Formbutton next" type="<?php echo $this->buttonType; ?>" onclick="<?php echo $this->next['click']; ?>" accesskey="n"<?php echo $this->next['disabled']; ?>>
            <?php echo $this->getIcon($this->next['icon'], '', 16); ?>
        </button>
        <button class="Formbutton last" type="<?php echo $this->buttonType; ?>" onclick="<?php echo $this->last['click']; ?>" accesskey="m"<?php echo $this->last['disabled']; ?>>
            <?php echo $this->getIcon($this->last['icon'], '', 16); ?>
        </button>
    </div>
</form>
<script type="text/javascript">
$(function() {
    $("#combobox").combobox();
});
</script>
