<?php
echo $this->doctype();
$version = new Msd_Version();
?>
<html>
<head>
    <title>MySQLDumper <?php echo $version->getMsdVersion();?> Error</title>
    <?php
        echo $this->headMeta() . "\n";
        echo $this->headScript() . "\n";
    ?>
</head>
<body>
<?php
if ($this->displayErrors == 1) {
?>
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
      <br>
        Controller:
            <span id="controller">
                <?php echo $this->request->getParam('controller'); ?>
            </span>
      <br>
        Action:
            <span id="action">
                <?php echo $this->request->getParam('action'); ?>
            </span>
      <br>
        Module:
            <span id="module">
                <?php echo $this->request->getParam('module'); ?>
            </span>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif;
}
?>
</body>
</html>