<div id="panel_db" class="panel">
    <fieldset>
        <legend><?php echo $this->lang->L_CONNECTIONPARS;?></legend>
        <div id="connection-params" style="display:none;">
            <table style="width:100%" summary="Databases">
                <tr class="row-even">
                    <td><?php echo $this->lang->L_DB_HOST;?>:</td>
                    <td>
                        <input class="text" type="text" name="dbhost"
                            value="<?php echo $this->escape($this->dbHost);?>" />
                    </td>
                </tr>
                <tr class="row-odd">
                    <td><?php echo $this->lang->L_DB_USER;?>:</td>
                    <td><input class="text" type="text" name="dbuser"
                        value="<?php echo$this->escape($this->dbUser);?>" size="20" />
                    </td>
                </tr>
                <tr class="row-even">
                    <td><?php echo $this->lang->L_DB_PASS;?>:</td>
                    <td><input class="text" type="password" name="dbpass"
                        value="<?php echo $this->escape($this->dbPass);?>" size="20" />
                    </td>
                </tr>
                <tr class="row-odd">
                    <td colspan="2">
                        <br /><strong><?php echo $this->lang->L_EXTENDEDPARS;?></strong>
                    </td>
                </tr>
                <tr class="row-even">
                    <td><?php echo $this->lang->L_PORT;?>:</td>
                    <td>
                        <input class="text" type="text" name="dbport"
                            value="<?php echo $this->escape($this->dbPort);?>" />
                    </td>
                </tr>
                <tr class="row-odd">
                    <td><?php echo $this->lang->L_SOCKET;?>:</td>
                    <td>
                        <input class="text" type="text" name="dbsocket"
                            value="<?php echo $this->escape($this->dbSocket);?>" />
                    </td>
                </tr>
                <tr class="row-even">
                    <td><?php echo $this->lang->L_ADD_DB_MANUALLY;?>:</td>
                    <td>
                        <input class="text" type="text" name="add_db_manual" value="" />
                    </td>
                </tr>
                <?php if ($this->dbAddedMessage > '') { ?>
                <tr class="row-odd">
                    <td colspan="2" class="error">
                        <?php echo $this->escape($this->dbAddedMessage);?>
                    </td>
                </tr>
                <?php } ?>
                <tr class="row-even">
                    <td>&nbsp;</td>
                    <td>
                        <p style="padding-left:8px;">
                            <button class="Formbutton" type="submit" name="save">
                                <?php echo $this->getIcon('save');?> <?php echo $this->lang->L_SAVE;?>
                            </button>
                        </p>
                    </td>
                </tr>
            </table>
        </div>

        <div>
        <script type="text/javascript">
        $(document).ready(function(){
            $('#toggler').toggle(
                    function(){
                        $('#connection-params').slideDown(400);
                        $('#toggleImage').attr('src', '<?php echo $this->getIconSrc("ArrowUp", 16);?>');
                    }, function(){
                        $('#connection-params').slideUp(400);
                        $('#toggleImage').attr('src', '<?php echo $this->getIconSrc("ArrowDown", 16);?>');
                    });
        });
        </script>
            <button type="button" class="Formbutton" id="toggler">
                <img  id="toggleImage" src="<?php echo $this->getIconSrc("ArrowDown", 16);?>" alt="" /> <?php echo $this->lang->L_FADE_IN_OUT;?>
            </button>
        </div>
    </fieldset>
    <br />
    <fieldset>
        <legend><?php echo $this->lang->L_DB_BACKUPPARS;?></legend>
        <table style="width:100%" summary="Backup parameters">
            <tr class="thead">
                <th class="right">#</th>
                <th><?php echo $this->lang->L_DB;?></th>
                <th class="left"><?php echo $this->lang->L_DUMP;?></th>
                <th><?php echo $this->lang->L_PREFIX;?></th>
                <th><?php echo $this->lang->L_COMMAND_BEFORE_BACKUP;?></th>
                <th><?php echo $this->lang->L_COMMAND_AFTER_BACKUP;?></th>
            </tr>
            <tr class="row-even">
                <td colspan="2">&nbsp;</td>
                <td class="left" colspan="4">
                    <a href="javascript:SelectMD(true,'<?php echo $this->nrOfDatabases;?>')"
                        class="small"><?php echo $this->getIcon('plus');?>
                    </a>
                    <a href="javascript:SelectMD(false,'<?php echo $this->nrOfDatabases;?>')"
                        class="small"><?php echo $this->getIcon('minus');?>
                    </a>
                </td>
            </tr>
<?php
$dbs = $this->config->getParam('databases');
echo $this->partial(
    'config/databases/listDbs.phtml',
    array('databases' => $dbs,
        'dbActual' => $this->dynamicConfig->getParam('dbActual'),
        'parent' => $this,
    )
);
?>
            <tr class="row-even">
                <td colspan="2">&nbsp;</td>
                <td class="left" colspan="4">
                    <a href="javascript:SelectMD(true,'<?php echo $this->nrOfDatabases;?>')"
                        class="small"><?php echo $this->getIcon('plus');?></a>
                    <a href="javascript:SelectMD(false,'<?php echo $this->nrOfDatabases;?>')"
                        class="small"><?php echo $this->getIcon('minus');?></a>
               </td>
            </tr>
            <?php if ($this->nrOfDatabases == 0) { ?>
                <tr><td><?php echo $this->lang->L_NO_DB_FOUND;?></td></tr>
            <?php } ?>
        </table>
    </fieldset>
</div>
