<?php
if ($this->pageCount) {
    if($this->current>1) { ?>
    <a href="<?php echo $this->url(array('offset'=>$this->first)) ?>"
         accesskey="f" class="Formbutton"><?php echo $this->getIcon('First', '', 16);?>
    </a>
    <?php
    } else { ?>
        <button class="Formbutton" disabled="disabled"><?php echo $this->getIcon('FirstDisabled', '', 16);?></button>
    <?php
    }

    if($this->previous != null) { ?>
        <a href="<?php echo $this->url(array('offset'=>$this->previous)) ?>"
            accesskey="c" class="Formbutton">
                <?php echo $this->getIcon('Back', '', 16);?>
        </a>
    <?php
    } else { ?>
        <button class="Formbutton" disabled="disabled"><?php echo $this->getIcon('BackDisabled', '', 16);?></button>
    <?php
    }
    ?>

    <select>
        <?php for($i=1; $i <= $this->pageCount; $i++) { ?>
                <option <?php if ($i == $this->current) echo 'selected="selected"'; ?>><?php echo $i; ?></option>
        <?php } ?>
    </select>

    <?php
    if($this->next != null) { ?>
        <a href="<?php echo $this->url(array('offset'=>$this->next)) ?>"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
        </a>
    <?php
    } else { ?>
        <button class="Formbutton" disabled="disabled"><?php echo $this->getIcon('ForwardDisabled', '', 16);?></button>
    <?php
    }

    if ($this->current<$this->last) { ?>
        <a href="<?php echo $this->url(array('offset'=>$this->last));?>"
            accesskey="f" class="Formbutton"><?php echo $this->getIcon('Last', '', 16);?>
        </a>
    <?php
    } else { ?>
        <button class="Formbutton" disabled="disabled"><?php echo $this->getIcon('LastDisabled', '', 16);?></button>
    <?php
    }
}  ?>
